swagger: '2.0'
info:
  title: Basic Login Form
  version: 1.0.0
  description: HTML Injection'"><a href=https://example.com><h1>Click here to login</h1></a>

paths:
  /test:
    get:
      summary: Simple login
      produces: [text/html]
      responses:
        200:
          description: Login form
          x-amazon-apigateway-integration:
            type: mock
            responses:
              default:
                statusCode: "200"
                responseTemplates:
                  text/html: |
                    <!DOCTYPE html><title>HTMLI</title>
